#######################################################
#                    Constants
#######################################################

# Android
ANDROID_PROJECT_DIR = "android"

# iOS
IOS_WORKSPACE = "ios/TestJest.xcworkspace"
IOS_SCHEME = "TestJest"
IOS_CONFIGURATION = "Debug"
IOS_SIMULATOR = "iPhone 16"
IOS_APP_NAME = "TestJest.app"
IOS_BUNDLE_ID = "org.reactjs.native.example.TestJest"
FIREBASE_APP_ID ="1:414182792740:android:fed42b913daba69e6142b1"

DEBUG_APK_PATH = "android/app/build/outputs/apk/debug/app-debug.apk"
RELEASE_APK_PATH = "android/app/build/outputs/apk/release/app-release.apk"
RELEASE_AAB_PATH = "android/app/build/outputs/bundle/release/app-release.aab"

FIREBASE_CREDENTIALS = "secrets/firebase-service-account.json"

#######################################################
#                    Android
#######################################################

platform :android do

  desc "Clean Android project"
  lane :clean do
    gradle(
      task: "clean",
      project_dir: ANDROID_PROJECT_DIR
    )
  end

  desc "Run ESLint for TypeScript/JavaScript"
  lane :eslint do
    sh("yarn lint")
  end

  # desc "Run Unit Tests"
  # lane :test do
  #   sh("yarn test")
  # end

  desc "Build Debug APK"
  lane :build_debug do
    gradle(
      task: "assembleDebug",
      project_dir: ANDROID_PROJECT_DIR
    )
  end

  desc "Install Debug APK"
  lane :install_debug do
    gradle(
      task: "installDebug",
      project_dir: ANDROID_PROJECT_DIR
    )
  end

  desc "Build Release APK"
  lane :build_release do
    gradle(
      task: "assembleRelease",
      project_dir: ANDROID_PROJECT_DIR
    )
  end

  desc "Build Release App Bundle (AAB)"
  lane :build_aab do
    gradle(
      task: "bundleRelease",
      project_dir: ANDROID_PROJECT_DIR
    )
  end

  # desc "Increment Android version code"
  # lane :increment_version do

  #   version_file = File.join(FastlaneCore::FastlaneFolder.path, "..", "android", "version.properties")
  #   version_file = File.expand_path(version_file)
  #   properties = {}

  #   File.readlines(version_file).each do |line|
  #     key, value = line.strip.split("=")
  #     properties[key] = value
  #   end

  #   current_version = properties["VERSION_CODE"].to_i
  #   new_version = current_version + 1

  #   properties["VERSION_CODE"] = new_version.to_s

  #   File.open(version_file, "w") do |file|
  #     properties.each do |key, value|
  #       file.puts("#{key}=#{value}")
  #     end
  #   end

  #   UI.success("🚀 VERSION_CODE updated: #{current_version} → #{new_version}")
  # end

  desc "Upload Debug APK to Firebase App Distribution"
  lane :firebase do
    build_debug

    firebase_app_distribution(
      app: FIREBASE_APP_ID,
      android_artifact_type: "APK",
      android_artifact_path: DEBUG_APK_PATH,
      service_credentials_file: FIREBASE_CREDENTIALS,
      release_notes_file: "artifacts/release-notes.md",
      groups: "qa",
      
      # release_notes: "Uploaded via Fastlane",
      # release_notes: last_git_commit[:message]
      # release_notes: changelog_from_git_commits 
    )
  end

  desc "Upload Release APK to Firebase App Distribution"
    lane :firebase_release do
      firebase_app_distribution(
        app: FIREBASE_APP_ID,
        android_artifact_type: "APK",
        android_artifact_path: RELEASE_APK_PATH,
        service_credentials_file: FIREBASE_CREDENTIALS,
        release_notes_file: "artifacts/release-notes.md",
        groups: "qa",
      )
    end

  desc "Development workflow"
  lane :dev do
    clean
    eslint
    # increment_version
    # test
    # build_debug
    # install_debug
    build_release
    # build_aab
    firebase_release
    UI.message("🚀 APK is ready and deploy to firebase")
  end

end

#######################################################
#                       iOS
#######################################################

platform :ios do

  desc "Clean iOS Derived Data"
  lane :clean do
    clear_derived_data
  end

  desc "Run ESLint"
  lane :eslint do
    sh("yarn lint")
  end

  desc "Build Debug app for iOS Simulator"
  lane :build_debug do
    build_app(
      workspace: IOS_WORKSPACE,
      scheme: IOS_SCHEME,
      configuration: IOS_CONFIGURATION,
      sdk: "iphonesimulator",
      destination: "generic/platform=iOS Simulator",
      skip_archive: true,
      skip_package_ipa: true,
      skip_codesigning: true,
      xcargs: "CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO"
    )

    ENV["APP_PATH"] = sh(
      "find ~/Library/Developer/Xcode/DerivedData -name '#{IOS_APP_NAME}' | tail -1"
    ).strip

    UI.success("📱 App built successfully")
    UI.message("📦 #{ENV['APP_PATH']}")
  end

  desc "Boot iOS Simulator"
  lane :boot_simulator do |options|
    simulator = options[:device] || IOS_SIMULATOR

    sh("open -a Simulator")
    sh("xcrun simctl boot '#{simulator}' || true")
  end

  desc "Install app on booted simulator"
  lane :install_debug do
    app_path = ENV["APP_PATH"]

    if app_path.to_s.empty?
      app_path = sh(
        "find ~/Library/Developer/Xcode/DerivedData -name '#{IOS_APP_NAME}' | tail -1"
      ).strip
    end

    UI.user_error!("#{IOS_APP_NAME} not found.") if app_path.empty?

    sh("xcrun simctl install booted '#{app_path}'")
  end

  desc "Launch app"
  lane :launch_app do
    sh("xcrun simctl launch booted #{IOS_BUNDLE_ID}")
  end

  desc "Development workflow"
  lane :dev do
    clean
    eslint
    build_debug
    boot_simulator
    install_debug
    launch_app
  end

end