name: React Native CI

# on:
#   workflow_dispatch:

# on:
#   push:
#     branches:
#       - main
#       - develop

#   pull_request:
#     branches:
#       - main
#       - develop
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.4'
      #     bundler-cache: true

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Ruby Dependencies
        run: bundle install

      - name: Type Check
        run: yarn tsc --noEmit

      - name: Lint
        run: yarn lint

      - name: Check Formatting
        run: yarn prettier --check .

      - name: Generate Release Notes
        shell: bash
        run: |
          mkdir -p artifacts

          VERSION_NAME=$(grep VERSION_NAME android/version.properties | cut -d'=' -f2)
          VERSION_CODE=$(grep VERSION_CODE android/version.properties | cut -d'=' -f2)

          cat > artifacts/release-notes.md <<EOF
          🚀 React Native Lab

          📅 Release Date
          $(date +"%d %b %Y %I:%M %p")

          📦 Version
          ${VERSION_NAME} (${VERSION_CODE})

          🌿 Branch
          ${{ github.head_ref }}

          📌 Pull Request
          ${{ github.event.pull_request.title }}

          👤 Author
          ${{ github.actor }}

          ----------------------------------------

          ${{ github.event.pull_request.body }}

          ----------------------------------------

          🤖 Built Automatically via GitHub Actions + Fastlane
          EOF

      - name: Create Firebase Service Account
        run: |
          mkdir -p secrets
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > secrets/firebase-service-account.json

      - name: Run Fastlane Android Development Workflow
        run: bundle exec fastlane android dev

      - name: Notify Slack
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          VERSION_NAME=$(grep VERSION_NAME android/version.properties | cut -d'=' -f2)
          VERSION_CODE=$(grep VERSION_CODE android/version.properties | cut -d'=' -f2)

          MESSAGE="🚀 React Native Lab

          Version: ${VERSION_NAME} (${VERSION_CODE})

          Branch: ${{ github.head_ref }}

          Developer: ${{ github.actor }}

          PR: ${{ github.event.pull_request.title }}

          ${{ github.event.pull_request.body }}"

          jq -n \
            --arg text "$MESSAGE" \
            '{text:$text}' > payload.json

          cat payload.json

          curl \
            -X POST \
            -H "Content-Type: application/json" \
            --data @payload.json \
            "$SLACK_WEBHOOK_URL"

      # - name: Run Tests
      # run: yarn test
