name: React Native CI

on:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
# name: React Native CI

# on:
#   workflow_dispatch:

# jobs:
#   hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Say Hello
#         run: echo "Hello GitHub Actions 🚀"
